language: node_js
node_js:
- '10'
before_script:
- npm install -g gulp-cli
script:
- npm run build
deploy:
  provider: npm
  email: support@travellink.com.au
  skip_cleanup: true
  node: '10.0'
  api_key:
    secure: CF9OvK5vrGdGeuYIWIaw5mr0tqFKNN5ta10Rbbgg2C1BbA4oM6iGVgQltawxnFmZn7sjv5OkRDHvOlzZuvLwd2Ntxh1lXaSJTDsgc4IFW6dkQmzk8V9uWwyFMHXqGBwIe5W+EOcSe1FUf20YlwvAfn0QumwKslWERpGy73vmg6sb95OFw7EhiLdoXRLoT7aJgIHzvWz1oGqam1d7YFFlqXFMmn2ytroKyiuus/FM6KLYrmNRob5lE/7c7LrvaZiRT/w6QulI3q+XSqPwTmtSs04Tzzv5kY8JrU09/5FCHNwr3hHt8/mI5YL36arNewDeZ7kufEExAYu4VTodIXvyYjQAiAgEgCq1FyTiv7WzCgHtLKcMw/CG7Y6Ia93uXkNMqTzHEey3kygy7e5/5l6JrWTz8rPoUzp3BYPkzr/PLztP+QVSRG0kAbBLHm7XkmVKLVlDXYhj7uGufY0EF+EILs21qZTSA0kCA+kHPW0O1BKHvSMrtTqXRA8LNbgyFOy5AIuRclIkQbpyUA83LgdpLl8toDWb9WoIeXseNZSb9trMxL5WH0Nrx+QBK5yVuPnh7VAR/OsGuMz9Nssnm3CfF0Mk1Oyh4kzJIFFpW4/3mS42Wdpid8Dd8cLgjvtITucF4+q/QUoXGhbHVFFklkdvTm43DRF4bRBZjA7ipz/dcTU=
  on:
    all_branches: true
    tags: true
