language: node_js
node_js:
- '10'
before_script:
- npm install -g gulp-cli
script:
- npm run build
deploy:
  provider: npm
  email: support@travellink.com.au
  skip_cleanup: true
  node: '10.0'
  api_key:
    secure: Gx35bUa5zHEMarB5fhOLpLMUfLFAu+NrMa6i4LcfC8UXrFbn1hNX0pZkJCsCIdcuFETbSs0NHZuZlyTsCeRnuysPsGmw/I5IAE8K6BQxF2yr8/09Zu8FLEyWTT61CA2F+rXcpHJNlAX0jKVtgtjL5B3OBT8wr6N5vAfW0w4awYrZLDaGcL5KLN1gQ+VYwkPiT51fTwutWi8PDxKl+z7DETSON/gqzdQTP/IsZm4A9mmMfdBbzdEQ2A+n2M/OLqIY2VmLdI1zdtg3urDUpYSRXJ23UY/tPYcGkKLfWwRmDwHO9FUH48hs5lPtYDzZmPNijc40InY3W8wXKvgZYRdyWKyTbg2r4pcp40dwxf55A32IDijElsS4SGOqddBdoTYv85UA/nhElB3kPMIbYEQNaI7RPylyIpD0DELw4cdopcehalc9juIID+JLPnHwM13evJ5SVmlE7YwHMR0pc0tQPZBzncDTsywU4APoE9i2PdMh9JD+awlF3cac/UJuAWtOl65rjoMIVsa7mmxPrrzph0U+ESxB8jpidFM9M7IW2U8cXv2N30gPhXWP/uK2ZBWu+pK/CCbPMB2EL70kA/A0lH5TCHCkJUBRcV2F9013bdrd/RkaG3cr1q2laUfSoD+cQJSvnD7qUPQiqNPwAqMyjEn6vS3pK7skMWE4BaczWJA=
  on:
    all_branches: true
    tags: true
